# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


#' Causal Online Random Forest 
#'
#' Create a Causal Online Random Forest and fit on provided data. 
#' @param x A matrix of features on which to generate predictions.  Must be equal to `numFeatures` when forest was initialized.
#' @param y Vector of classes.  Multiclass classification is supported.  Must be integers.
#' @param treat Vector of treatment assignment.  Must be 0 or 1.
#' @param numRandomTests Number of random tests, i.e., number of features to be selected at each node for evaluation.
#' @param counterThreshold Threshold for number of observations before a split will occur.
#' @param maxDepth Maximum depth for each tree.
#' @param numTrees Number of trees in the forest.
#' @param numEpochs Number of epochs for processing during each training step.
#' @param type Type of Random Forest.  Only `classification` is implemented at this time.
#' @param method Method used for determining if a node should split.  Implemented methods are `gini` for Gini Impurity or `entropy` for entropy.
#' causal_online_random_forest()
#' 

causal_online_random_forest <- function(x, y, treat, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type = "classification", method = "gini", causal = TRUE, findTrainError = FALSE, verbose = FALSE, trainModel = TRUE) {
    .Call('_corf_causal_online_random_forest', PACKAGE = 'corf', x, y, treat, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type, method, causal, findTrainError, verbose, trainModel)
}

#' Online Random Forest 
#'
#' Create an Online Random Forest and fit on provided data. 
#' @param x A matrix of features on which to generate predictions.  Must be equal to `numFeatures` when forest was initialized.
#' @param y Vector of classes.  Multiclass classification is supported.  Must be integers.
#' @param treat Vector of treatment assignment.  Must be 0 or 1.
#' @param numClasses Number of classes expected to be classified.
#' @param numFeatures Number of features that will be in the learning dataset.
#' @param numRandomTests Number of random tests, i.e., number of features to be selected at each node for evaluation.
#' @param counterThreshold Threshold for number of observations before a split will occur.
#' @param maxDepth Maximum depth for each tree.
#' @param numTrees Number of trees in the forest.
#' @param numEpochs Number of epochs for processing during each training step.
#' @param type Type of Random Forest.  Only `classification` is implemented at this time.
#' @param method Method used for determining if a node should split.  Implemented methods are `gini` for Gini Impurity or `entropy` for entropy.
#' online_random_forest()

online_random_forest <- function(x, y, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type = "classification", method = "gini", findTrainError = FALSE, verbose = FALSE, trainModel = TRUE) {
    .Call('_corf_online_random_forest', PACKAGE = 'corf', x, y, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type, method, findTrainError, verbose, trainModel)
}

orf <- function(x, y, orfModel, trainModel = TRUE) {
    .Call('_corf_orf', PACKAGE = 'corf', x, y, orfModel, trainModel)
}

corf <- function(x, y, treat, orfModel, trainModel = TRUE) {
    .Call('_corf_corf', PACKAGE = 'corf', x, y, treat, orfModel, trainModel)
}

predictOrf <- function(x, orfModel, iteAll = FALSE) {
    .Call('_corf_predictOrf', PACKAGE = 'corf', x, orfModel, iteAll)
}

roundup <- function(x) {
    .Call('_corf_roundup', PACKAGE = 'corf', x)
}

#' Causal Online Random Forest Cross Validation
#'
#' This function runs cross validation with a Causal ORF over a dataset to return out of sample predictions and accuracy.
#' @param x A matrix of features on which to generate predictions.  Must be equal to `numFeatures` when forest was initialized.
#' @param y Vector of classes.  Multiclass classification is supported.  Must be integers.
#' @param treat Vector of treatment assignment.  Must be 0 or 1.
#' @param numClasses Number of classes expected to be classified.
#' @param numFeatures Number of features that will be in the learning dataset.
#' @param numRandomTests Number of random tests, i.e., number of features to be selected at each node for evaluation.
#' @param counterThreshold Threshold for number of observations before a split will occur.
#' @param maxDepth Maximum depth for each tree.
#' @param numTrees Number of trees in the forest.
#' @param numEpochs Number of epochs for processing during each training step.
#' @param type Type of Random Forest.  Only `classification` is implemented at this time.
#' @param method Method used for determining if a node should split.  Implemented methods are `gini` for Gini Impurity or `entropy` for entropy.


causal_orf_cv <- function(x, y, treat, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type = "classification", method = "gini") {
    .Call('_corf_causal_orf_cv', PACKAGE = 'corf', x, y, treat, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type, method)
}

#' Online Random Forest Cross Validation
#'
#' This function runs cross validation with an ORF over a dataset to return out of sample predictions and accuracy.
#' @param x A matrix of features on which to generate predictions.  Must be equal to `numFeatures` when forest was initialized.
#' @param y Vector of classes.  Multiclass classification is supported.  Must be integers.
#' This function initializes the online random forest (or causal online random forest).
#' @param numClasses Number of classes expected to be classified.
#' @param numFeatures Number of features that will be in the learning dataset.
#' @param numRandomTests Number of random tests, i.e., number of features to be selected at each node for evaluation.
#' @param counterThreshold Threshold for number of observations before a split will occur.
#' @param maxDepth Maximum depth for each tree.
#' @param numTrees Number of trees in the forest.
#' @param numEpochs Number of epochs for processing during each training step.
#' @param type Type of Random Forest.  Only `classification` is implemented at this time.
#' @param method Method used for determining if a node should split.  Implemented methods are `gini` for Gini Impurity or `entropy` for entropy.
#' @keywords causal random forest, online learning, incremental learning, out-of-core learning, online random forest
#' orf_cv()
#' 

orf_cv <- function(x, y, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type = "classification", method = "gini") {
    .Call('_corf_orf_cv', PACKAGE = 'corf', x, y, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type, method)
}

getImps_ <- function(orfModel) {
    .Call('_corf_getImps_', PACKAGE = 'corf', orfModel)
}

