# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

causal_online_random_forest <- function(x, y, treat, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type = "classification", method = "gini", findTrainError = FALSE, verbose = FALSE, trainModel = TRUE) {
    .Call('_corf_causal_online_random_forest', PACKAGE = 'corf', x, y, treat, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type, method, findTrainError, verbose, trainModel)
}

online_random_forest <- function(x, y, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type = "classification", method = "gini", findTrainError = FALSE, verbose = FALSE, trainModel = TRUE) {
    .Call('_corf_online_random_forest', PACKAGE = 'corf', x, y, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, type, method, findTrainError, verbose, trainModel)
}

orf <- function(x, y, orfModel, trainModel = TRUE) {
    .Call('_corf_orf', PACKAGE = 'corf', x, y, orfModel, trainModel)
}

corf <- function(x, y, treat, orfModel, trainModel = TRUE) {
    .Call('_corf_corf', PACKAGE = 'corf', x, y, treat, orfModel, trainModel)
}

predictOrf <- function(x, orfModel, allTrees = FALSE) {
    .Call('_corf_predictOrf', PACKAGE = 'corf', x, orfModel, allTrees)
}

causal_orf_cv <- function(x, y, treat, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type = "classification", method = "gini") {
    .Call('_corf_causal_orf_cv', PACKAGE = 'corf', x, y, treat, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type, method)
}

orf_cv <- function(x, y, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type = "classification", method = "gini") {
    .Call('_corf_orf_cv', PACKAGE = 'corf', x, y, numClasses, numRandomTests, counterThreshold, maxDepth, numTrees, numEpochs, nfolds, type, method)
}

getImps_ <- function(orfModel) {
    .Call('_corf_getImps_', PACKAGE = 'corf', orfModel)
}

